# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars'
puts "Destroying old ingredients, doses, and cocktails"
Dose.destroy_all
Ingredient.destroy_all
Cocktail.destroy_all
puts "Creating new ingredients"
Ingredient.create(name: "Light rum")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Applejack")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Dark rum")
Ingredient.create(name: "Sweet Vermouth")
Ingredient.create(name: "Strawberry schnapps")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Apricot brandy")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Southern Comfort")
Ingredient.create(name: "Orange bitters")
Ingredient.create(name: "Brandy")
Ingredient.create(name: "Lemon vodka")
Ingredient.create(name: "Blended whiskey")
Ingredient.create(name: "Dry Vermouth")
Ingredient.create(name: "Amaretto")
Ingredient.create(name: "Tea")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "A\u00f1ejo rum")
Ingredient.create(name: "Bitters")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Kahlua")
Ingredient.create(name: "demerara Sugar")
Ingredient.create(name: "Dubonnet Rouge")
Ingredient.create(name: "Lime juice")
Ingredient.create(name: "Irish whiskey")
Ingredient.create(name: "Apple brandy")
Ingredient.create(name: "Carbonated water")
Ingredient.create(name: "Cherry brandy")
Ingredient.create(name: "Creme de Cacao")
Ingredient.create(name: "Grenadine")
Ingredient.create(name: "Port")
Ingredient.create(name: "Coffee brandy")
Ingredient.create(name: "Red wine")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Grapefruit juice")
Ingredient.create(name: "Ricard")
Ingredient.create(name: "Sherry")
Ingredient.create(name: "Cognac")
Ingredient.create(name: "Sloe gin")
Ingredient.create(name: "Apple juice")
Ingredient.create(name: "Pineapple juice")
Ingredient.create(name: "Lemon juice")
Ingredient.create(name: "Sugar syrup")
Ingredient.create(name: "Milk")
Ingredient.create(name: "Strawberries")
Ingredient.create(name: "Chocolate syrup")
Ingredient.create(name: "Yoghurt")
Ingredient.create(name: "Mango")
Ingredient.create(name: "Ginger")
Ingredient.create(name: "Lime")
Ingredient.create(name: "Cantaloupe")
Ingredient.create(name: "Berries")
Ingredient.create(name: "Grapes")
Ingredient.create(name: "Kiwi")
Ingredient.create(name: "Tomato juice")
Ingredient.create(name: "Cocoa powder")
Ingredient.create(name: "Chocolate")
Ingredient.create(name: "Heavy cream")
Ingredient.create(name: "Galliano")
Ingredient.create(name: "Peach Vodka")
Ingredient.create(name: "Ouzo")
Ingredient.create(name: "Coffee")
Ingredient.create(name: "Spiced rum")
Ingredient.create(name: "Water")
Ingredient.create(name: "Espresso")
Ingredient.create(name: "Angelica root")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Cranberries")
Ingredient.create(name: "Johnnie Walker")
Ingredient.create(name: "Apple cider")
Ingredient.create(name: "Everclear")
Ingredient.create(name: "Cranberry juice")
Ingredient.create(name: "Egg yolk")
Ingredient.create(name: "Egg")
Ingredient.create(name: "Grape juice")
Ingredient.create(name: "Peach nectar")
Ingredient.create(name: "Lemon")
Ingredient.create(name: "Firewater")
Ingredient.create(name: "Lemonade")
Ingredient.create(name: "Lager")
Ingredient.create(name: "Whiskey")
Ingredient.create(name: "Absolut Citron")
Ingredient.create(name: "Pisco")
Ingredient.create(name: "Irish cream")
Ingredient.create(name: "Ale")
Ingredient.create(name: "Chocolate liqueur")
Ingredient.create(name: "Midori melon liqueur")
Ingredient.create(name: "Sambuca")
Ingredient.create(name: "Cider")
Ingredient.create(name: "Sprite")
Ingredient.create(name: "7-Up")
Ingredient.create(name: "Blackberry brandy")
Ingredient.create(name: "Peppermint schnapps")
Ingredient.create(name: "Creme de Cassis")
Ingredient.create(name: "Jack Daniels")
puts "Creating new cocktails"
Cocktail.create!(name: "Rusty Nail", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305106/Mister%20Cocktail/photo-1482349212652-744925892164_u3hsct.jpg"))
Cocktail.create!(name: "Citrus Distillery", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573304892/Mister%20Cocktail/photo-1453825012366-3738046cb6c7_hvhmbn.jpg"))
Cocktail.create!(name: "Bloody Barry", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305020/Mister%20Cocktail/photo-1568100119359-dd8eec0b1ca3_ylqhza.jpg"))
Cocktail.create!(name: "Breaking Bad", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305177/Mister%20Cocktail/photo-1461823385004-d7660947a7c0_sd96xt.jpg"))
Cocktail.create!(name: "Whiskey Whiskers", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305158/Mister%20Cocktail/photo-1470337458703-46ad1756a187_hhckfn.jpg"))
Cocktail.create!(name: "Clouded Judgement", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305011/Mister%20Cocktail/photo-1558950334-8d04704332f8_q37x01.jpg"))
Cocktail.create!(name: "Antidote", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305119/Mister%20Cocktail/photo-1570629557357-45c6767e0140_azank2.jpg"))
Cocktail.create!(name: "Invisibile", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305040/Mister%20Cocktail/photo-1571291731905-9fd9805bc584_ylwcqs.jpg"))
Cocktail.create!(name: "Bloody Cola", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573304976/Mister%20Cocktail/photo-1551751299-1b51cab2694c_mo5aig.jpg"))
Cocktail.create!(name: "Lean Green", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305029/Mister%20Cocktail/photo-1455621481073-d5bc1c40e3cb_h1h9q2.jpg"))
Cocktail.create!(name: "High Tea", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305141/Mister%20Cocktail/photo-1560461698-f3c2a1b15364_fbuvpn.jpg"))
Cocktail.create!(name: "Passion", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573304900/Mister%20Cocktail/photo-1542600176-9d2c4bb4bc1a_t4qv3n.jpg"))
Cocktail.create!(name: "Papa Smurf", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305197/Mister%20Cocktail/photo-1550555179-309357935820_ctihjs.jpg"))
Cocktail.create!(name: "Olive Garden", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573305054/Mister%20Cocktail/photo-1571577556441-cd4af9c209f3_cvbsdf.jpg"))
Cocktail.create!(name: "Rocky Mountain", photo: open("https://res.cloudinary.com/kenrick/image/upload/v1573304882/Mister%20Cocktail/photo-1514361892635-6b07e31e75f9_axfmew.jpg"))
puts "Creating new doses"
Dose.create!(description: "10mL", cocktail_id: 1, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 2, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 3, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 4, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 5, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 6, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 7, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 8, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 9, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 10, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 11, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 12, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 13, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 14, ingredient_id: 1)
Dose.create!(description: "10mL", cocktail_id: 15, ingredient_id: 1)
puts "done!"
